name: GitActionsDemo

on: [push]

jobs:
    echoStep:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Echo
              run: echo "This is a demo for GitHub Actions."
            - run: echo "This job was triggered by ${{ github.event_name }}, is running on ${{runner.os}} hosted by GitHub."
            - run: echo "The name of the branch is ${{github.ref}} and the repository is ${{ github.repository }}."
    
    helloworldCpp:
        runs-on: ubuntu-latest
        steps:
            - run: touch main.cpp
            - run: echo "#include <iostream>" >> main.cpp
            - run: echo "int main() { std::cout << \"Hello, world!\" << std::endl; return 0; }" >> main.cpp
            - name: Compile and Run
              run: g++ main.cpp -o main && ./main
