name: Complete GitHub Actions Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: "Hello, World!"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          TEST_ENV_VAR: ${{ secrets.TEST_ENV_VAR }}

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/

      - name: Set output value
        id: set_output
        run: echo "::set-output name=my_output::$(date)"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Print test results
        run: cat test-results/*

      - name: Deploy application
        run: echo "Deploying application with output: ${{ needs.build.outputs.my_output }}"
